"""empty message

Revision ID: 7fb6c703e02f
Revises: 7435b0a865e6
Create Date: 2019-09-13 07:35:49.741728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7fb6c703e02f"
down_revision = "7435b0a865e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_with_email",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        op.f("ix_users_with_email_id"), "users_with_email", ["id"], unique=False
    )
    op.alter_column(
        "users",
        "expert_mode",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "expert_mode",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_index(op.f("ix_users_with_email_id"), table_name="users_with_email")
    op.drop_table("users_with_email")
    # ### end Alembic commands ###
