"""empty message

Revision ID: 996866bb604e
Revises: 7435b0a865e6
Create Date: 2019-09-30 10:59:51.089666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "996866bb604e"
down_revision = "7435b0a865e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("picture_url", sa.String(), nullable=True))
    op.alter_column(
        "users",
        "expert_mode",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "expert_mode",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_column("users", "picture_url")
    # ### end Alembic commands ###
